--- Cargo.toml	2019-11-12 01:08:57.000000000 +0100
+++ Cargo.toml	2019-12-10 19:38:39.192990000 +0100
@@ -44,7 +44,7 @@ toml-query = "0.9.2"
 url = "1.7"
 walrus = "0.5"
 wasm-interface = { path = "lib/wasm-interface" }
-wasmer-runtime-core = "0.9.0"
+wasmer-runtime-core = "0.11.0"
 wasmparser = "0.39.2"
 whoami = "0.5"
 zstd = "0.4"
