--- Cargo.toml	2020-03-01 15:37:26 UTC
+++ Cargo.toml
@@ -44,7 +44,7 @@ toml-query = "0.9.2"
 url = "1.7"
 walrus = "0.5"
 wasm-interface = { path = "lib/wasm-interface" }
-wasmer-runtime-core = "0.9.0"
+wasmer-runtime-core = "0.14.1"
 wasmparser = "0.39.2"
 whoami = "0.5"
 zstd = "0.4"
