--- cargo-crates/minifb-0.13.0/Cargo.toml.orig	2020-03-16 17:22:29 UTC
+++ cargo-crates/minifb-0.13.0/Cargo.toml
@@ -40,6 +40,8 @@ features = ["winuser", "wingdi", "libloaderapi", "errh
 version = "2.18.3"
 [target.x86_64-unknown-dragonfly.dependencies.x11-dl]
 version = "2.18.3"
+[target.aarch64-unknown-freebsd.dependencies.x11-dl]
+version = "2.18.3"
 [target.x86_64-unknown-freebsd.dependencies.x11-dl]
 version = "2.18.3"
 [target.x86_64-unknown-linux-gnu.dependencies.x11-dl]
